version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - cangir
  assignees:
  - cangir
  ignore:
  - dependency-name: browserslist
    versions:
    - 4.16.1
    - 4.16.3
    - 4.16.4
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.2.0
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
    - 9.8.6
